<?php
/**
 * Implementation of hook_init()
 */
function chosen_init() {
  drupal_add_library('chosen', 'chosen');
  drupal_add_js(drupal_get_path('module', 'chosen') . '/includes/chosen.js');
}

/**
 * Implementation of hook_library()
 */
function chosen_library() {
  $libraries['chosen'] = array(
    'title' => 'Chosen', 
    'website' => 'http://harvesthq.github.com/chosen/', 
    'version' => '1.0', 
    'js' => array(
      drupal_get_path('module', 'chosen') . '/chosen/chosen.jquery.js' => array(),
    ), 
    'css' => array(
      drupal_get_path('module', 'chosen') . '/chosen/chosen.css' => array(
        'type' => 'file', 
        'media' => 'all',
      ),
    ),
  );
  return $libraries;
}