<?php
/**
 * Implementation of hook_init()
 */
function chosen_init() {
  drupal_add_js(drupal_get_path('module', 'chosen') .'/includes/chosen.js');
  drupal_add_css(drupal_get_path('module', 'chosen') .'/includes/chosen.css');
}

/**
 * Implementation of hook_preprocess_page().
 */
function chosen_preprocess_page(&$vars) {
  $chosen_path = drupal_get_path('module', 'chosen');
  $vars['styles'] = '
    <script src="/'. $chosen_path .'/includes/jquery-1.4.1.min.js" type="text/javascript"></script>
    <script src="/'. $chosen_path .'/chosen/chosen.jquery.js" type="text/javascript"></script>
    <script type="text/javascript">
      jq141 = jQuery.noConflict(true);
    </script>' . $vars['styles'] . '
    <link type="text/css" rel="stylesheet" href="/'. $chosen_path .'/chosen/chosen.css" />';
}
